spring:
  application:
    name: student
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/student_db?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&useSSL=false&characterEncoding=UTF-8&characterSetResults=UTF-8&createDatabaseIfNotExist=true&serverTimezone=Asia/Dhaka
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    enabled: true
    suffix: .html
    prefix: classpath:/templates/

server:
  port: 8081

files:
  upload:
    path: C:\Project_Files\student\doc